### ISSUE TITLE
Corporate Support activity areas vs GSBPM Overarching processes

### ISSUE THREAD

**Issue by FrancineK** [linked-statistics/COOS#1]
In the draft version of [GAMSO](https://statswiki.unece.org/download/attachments/241828930/GAMSO%20v1_2%2029%20Jan.docx?version=1&modificationDate=1548942693017&api=v2), we have the following **activities** under **Corporate Support** **activity area** :
- **Manage Quality** and 
- **Manage Information and Knowledge**. These include:
     1. Manage documents and records, including archiving and destruction
     2. Manage knowledge
     3. Manage information standards and access rights
     4. **Manage metadata and data**

They are the same as the GSBPM over arching processes: **quality management and metadata management**, but at different levels in GAMSO.

**Comment by FrancineK** [comment]
> The over-arching processes, both those that have a statistical component, and those that are more general, and could apply to any sort of organisation, that are mentioned in the GSBPM are not included in Production as they relate to other parts of the GAMSO.
-- [GAMSO](https://statswiki.unece.org/download/attachments/241828930/GAMSO%20v1_2%2029%20Jan.docx?version=1&modificationDate=1548942693017&api=v2)

I guess this answers Flavio's question about the level of GSBPM addressed in the Production Activity Area of GAMSO: it is **level 1**.

**Comment by FlavioRizzolo** [comment]
Interestingly, the above quote from GAMSO related to over-aching processes is from version 1.1 and has been deleted from 1.2 29 (January 2019). A note has been added:

> 39.	The GAMSO includes information and knowledge management activities at an organisational level. Metadata management activities that are more directly related to the statistical production are included in the GSBPM (for further information, see Section VI. Cross-cutting process of the GSBPM). 

Which seems to be a change of direction from version 1.1.

**Comment by FlavioRizzolo** [comment]
In other words, it seems that Production should include not only GSBPM level 0, a.k.a. the statistical business process (together with level 1 and 2), but also the overarching processes.

**Comment by FranckCo** [comment]
Notes from March 7 meeting:

 - OK to add the class Overarching Process.
- There is another issue related to the confusion between the GSBPM overarching processes and the GAMSO corporate support activities. We should check whether or not the new GAMSO version solves this.
 - If the overarching processes are in the corporate support, then the production activity is GSBPM level 0, 1, 2; if not, it is the whole GSBPM.

**Comment by FranckCo** [comment]
Comments on the March 7 meeting notes:

 - Could also be named OverarchingActity. Do we agree that it is a sub-class of StatisticalProductionActivity

**Comment by InKyungChoi** [comment]
Indeed there has been change in GAMSO (and in GSBPM also) to differentiate, e.g., "manage quality" in GAMSO which will be at corporate level (e.g. establishment of corporate quality framework) and "quality management" in GSBPM which will be at process level (e.g. monitoring quality of process using corporate framework). So GSBPM overarching process should be included in Production. 
Also, maybe name "overarching process" and descriptions should be changed, this creates so much confusion...

**Comment by FlavioRizzolo** [comment]
> 
> 
> Comments on the March 7 meeting notes:
> 
>     * Could also be named OverarchingActity. Do we agree that it is a sub-class of StatisticalProductionActivity

I think it is indeed a sub-class of StatisticalProductionActivity. I also like the name of OverarchingActity to that class.

**Comment by FranckCo** [comment]
Closed as decided at the May 7 meeting. See issue #11 for remaining question.
