### ISSUE TITLE
Classify GAMSO activities as Activity or StatisticalActivity

### ISSUE THREAD

**Issue by FranckCo** [linked-statistics/COOS#10]
Decision during 16 April VC:  instances of activities would be spread between those with statistical nature (e.g. methodology), which would be instances of StatisticalActivity, and those without statistical nature (e.g. logistic), which would be instances of Activity.

**Comment by FranckCo** [comment]
Decision during May 7 VC: affect to Juan.

**Comment by DrJMunozMx** [comment]
![image](https://user-images.githubusercontent.com/1855266/60523065-b2885600-9caf-11e9-86ae-805e09282f20.png)

**Comment by DrJMunozMx** [comment]
The diagram has been updated to add: Task, and the specialized StatisticalProductionTask
Add StatisticalProductionProcess as a specilized StatisticalProcess

**Comment by DrJMunozMx** [comment]
Classification of Activities, Statistical Activities, Tasks and Statistical Tasks from GAMSO 1.2
[Activity-StatisticalActivity.docx](https://github.com/linked-statistics/COOS/files/3412685/Activity-StatisticalActivity.docx)
[Activity-StatisticalActivity.pdf](https://github.com/linked-statistics/COOS/files/3412686/Activity-StatisticalActivity.pdf)

**Comment by InKyungChoi** [comment]
The more I think about this, the less certain I become whether it is even possible to classify GAMSO activity into either "statistical activity" and "non-statistical activity" because GAMSO activity is so high-level and generic. For example, (@FlavioRizzolo, correct me if I am wrong), the Statistics Canada's Enterprise Anchor Model (see below) has vertical layers of IT services that are, together, both statistical (e.g. generic system for E&I) and non-statistical (e.g. email, IT security). Is it right then to classify GAMSO Manage IT activity which reads like

> 44. These activities cover coordination and management of information and technology resources and solutions. They include the management of the physical security of data and shared infrastructures. These include: Manage IT assets and services; Manage IT security; Manage technological change

as an "activity" (hence, without statistical element in it)?

>  [Statistics Canada's Enterprise Anchor Model](https://www150.statcan.gc.ca/n1/pub/11-634-x/2016001/section3/chap2-eng.htm)
> ![fig3 2 6-eng](https://user-images.githubusercontent.com/10498769/63690752-c498f780-c80d-11e9-9f59-f518f757f119.png) 
>- An Infrastructure Layer—core infrastructure services related to storage, informatics, and infrastructure security. In the Government of Canada, a government organization responsible for government-wide infrastructure (Shared Services Canada) provides these services. Email is included in this layer in the model, as a mail service hosted by Shared Services Canada.
>- A Core Technology Platforms layer—the various platforms that are part of the Technology Architecture
>- A Core Information Services layer—the statistical and corporate information services used across the organization (e.g., registers, metadata and data management, information management, classifications management)
>- A Core Statistical Services layer—common, shared statistical functions such as those found in Statistics Canada's Generalized Systems (e.g., Banff E&I, G-SAM, G-Export, etc.). Creating reusable services can be a strong contributor to organization success.
>- A Core Production Segments layer—platforms for the different solution segments supporting statistical production, including the collection platform, dissemination, business statistics processing, social statistics processing (common tools), and census. It also includes corporate services platforms used in running the business.

**Comment by DrJMunozMx** [comment]
I agree with @InkyungChoi too, maybe this will make the classification easier to understand. I will make the correction, accordingly to this.

**Comment by FranckCo** [comment]
Decision during August 29 VC: only Manage Statistical Methodology (http://id.unece.org/activity/activity/3.2) and Manage Data Suppliers (http://id.unece.org/activity/activity/3.6) are instances of coos:StatisticalActivity. The other GAMSO activities are just instances of the higher-level coos:Activity.
