### ISSUE TITLE
Links between OverarchingActivity instances and Activity instances

### ISSUE THREAD

**Issue by FranckCo** [linked-statistics/COOS#11]
Identify and formalize links that exist between GAMSO activities and GSBPM over-arching processes (e.g. Manage Quality / Quality Management).

**Comment by FlavioRizzolo** [comment]
**GAMSO Manage Quality**: "The GAMSO includes quality management activities at an organisational level. Quality management activities that are more directly related to the statistical production (e.g. setting process quality targets and monitoring compliance, seeking and analysing user feedback) are included in the GSBPM". 

**GSBPM Quality Management**: Quality concerns _organisations_, _products_, _sources_ and _processes_. In the present framework, quality management overarching process refers to _product_ and _process_ quality. Quality at an institutional level (e.g. adoption of a Quality Policy or Quality Assurance Framework) is considered in the GAMSO.

**Comment by FlavioRizzolo** [comment]
**GAMSO Manage Information and Knowledge**: "The GAMSO includes information and knowledge management activities at an organisational level. Metadata management activities that are more directly related to the statistical production are included in the GSBPM (for further information, see Section VI. Cross-cutting process of the GSBPM)."

**GSBPM Metadata Management**: "Metadata has an important role and must be managed at an operational level within the statistical production process. When aspects of metadata management are considered at corporate or strategic level (e.g. there are metadata systems that impact large parts of the production system), it should be considered in the framework of the GAMSO."

**Comment by FlavioRizzolo** [comment]
It's not clear from the definitions whether there is an overlap between GAMSO and GSBPM in the overarching processes. The language in the GAMSO definitions is too ambiguous. Sentences like "GAMSO includes _X_",  and "_Y_ are included in the GSBPM" could be interpreted as _Y_ being included in both. It could also be interpreted differently. 

Similarly, the GSBPM phrasing doesn't exclude GAMSO, at least not conclusively. "When _X_ it should be considered in GAMSO" is not saying it shouldn't be considered in the GSBPM as well. It's not saying it should either. 

We need more precise statements in both models.

**Comment by FlavioRizzolo** [comment]
**GAMSO Manage Statistical Methodology** is an interesting one. Surprisingly (at least to me), we don't have anything similar in GSBPM. Shouldn't we have an overarching processing dealing with methodology management?

Another interesting one is **GSBPM Data Management**. Data management seems to be included in **GAMSO Manage Information and Knowledge** (the definition says "manage metadata and _data_" is included). However, when describing the relationship with GSBPM, only metadata management is mentioned. Is that an oversight or is it because data management is not really considered in GAMSO? It seems to me that data management should be part of GAMSO, which means that the relationship to GSBPM Data Management should be explicitly mentioned in the GAMSO documentation. Moreover, since it's a very important and broad topic, more information about data management should probably be added.

**Comment by FlavioRizzolo** [comment]
From GAMSO v1.2: 

"The Production activity area covers all steps necessary to design, implement and manage statistical production processes or cycles, including surveys, collections based on data from administrative or other sources and account compilations. They deliver the outputs approved under Strategy and Leadership, utilising the capabilities developed under Capability Development and the resources managed under Corporate Support.

The Production activities in the GAMSO are those included in the GSBPM version 5.1. This means that the GAMSO is by construction fully consistent with GSBPM."

The first paragraph seems to cover GSBPM phases but not overarching processes. The second paragraph seems to cover the whole GSBPM.

**Comment by FlavioRizzolo** [comment]
I suggest we go with the assumption that the **Production Activity Area** maps to the _whole GSBPM_, both phases and overarching processes. From that it follows that:

(i) **GAMSO Manage Quality** is disjoint from **GSBPM Quality Management** (covered in GAMSO Production) and 
(ii) **GAMSO Manage Information and Knowledge** is disjoint from **GSBPM Metadata Management** (also covered in GAMSO Production).

**Comment by InKyungChoi** [comment]
I agree with the assumption, it is my understanding that 

- Production Activity Area covers both phases and overarching processes

- GAMSO activities are disjoint, hence GSBPM OPs are non-overlapping with GAMSO Corporate Support Activities

- But above does not mean that they are independent. GSBPM OPs uses GAMSO Corporate Support Activities. GAMSO Corporate Support Activities supports GSBPM OPs and GSBPM phases.

Like below: 
![Statistical Activities](https://user-images.githubusercontent.com/10498769/59453813-04f0f800-8e11-11e9-9fde-419595ab83ef.png)

**Comment by FranckCo** [comment]
Decision during August 29 VC:

- Create "uses" and "supports" proprieties.

     StatisticalProductionActivity -> uses -> Activity
     Activity -> supports -> StatisticalProductionActivity

- Actual links between instances defined in the ontology limited to the "obvious" ones:

     Quality Management <- uses/supports -> Manage Quality
