### ISSUE TITLE
Introduce Task class

### ISSUE THREAD

**Issue by FranckCo** [linked-statistics/COOS#16]
Discussed during Unece MSWW on June 26: 'Activity' is used in COOS as a very broad term, in alignment to the PROV sense. But sometimes, 'Activity' evokes fine-grained activities that are smaller then GSBPM sub-processes (and contained in one of them). We need a specific term to convey this meaning. The term 'Task' was suggested.

The proposal is thus to create a 'Task' sub-class of StatisticalActivity which would be skos:narrower than coos:SubProcess.

**Comment by DrJMunozMx** [comment]
![image](https://user-images.githubusercontent.com/1855266/60260631-4b972580-98da-11e9-9c0d-4c8fd7fea9f6.png)

**Comment by DrJMunozMx** [comment]
This is a draft proposal to introduce the concept of Task and to have a balanced GAMSO-GSBPM terminology

GAMSO Defines 4 Activity Areas:
- Strategy and Leadership
- Capability Development
- Corporate Support
- Production
Activity Areas have Activities
Some Activities are Statistical Activities:
Like:
- Manage Statistical Methodology
- Produce Statistical Information
Processes have activities
The Statistical Process (described by GBPM) is a kind of process that contains StatisticalProductionActivities
Activities have Tasks, 
StatisticalProductionActivities are composed of StatisticalProductionTasks which are a kind of Tasks (specialized on the Production of Statistical Information)




1.

**Comment by FranckCo** [comment]
Decision during August 29 VC: agree to introduce Task with appropriate definition.
Proposal: "A task is a statistical activity which is scoped by a given GSBPM sub-process. Tasks can more or less fine-grained and form hierarchies."

**Comment by FranckCo** [comment]
Decision during September 19 VC: proposed definition (9e34320) adopted.
