### ISSUE TITLE
Add a Task object

### ISSUE THREAD

**Issue by FranckCo** [linked-statistics/COOS#21]
There was a consensus during ModernStats World Workshop 2019 to add a class representing smaller activities that would fit into GSBPM sub-processes and could be organized hierarchically.

The idea is not to make a list of tasks, but to create a common base class where NSIs could attach the tasks they have defined for their own use.

There is a Unece-MOS-SS task team starting in June for listing the tasks already defined by the different NSIs.

**Comment by FranckCo** [comment]
The Task class is defined in the Turtle file, but it has to be added to the HTML specification.

**Comment by JALinnerud** [comment]
Could the UNECE Classification of statistical activities https://statswiki.unece.org/display/CSA/CSA+Rev.+1 be relevant here?

**Comment by FranckCo** [comment]
Task also added in the HTML document (da371742d69ece06033914767ae697e9ef1fbd10) , but needs a better definition and examples.

**Comment by FranckCo** [comment]
Closing this issue and moving the question on CSA to a new issue (#33).
