### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by FranckCo** [linked-statistics/COOS#24]
The business case validated by the HLG-MOS specifies that the COOS ontology has to be available in English, French and Spanish.

English and French labels are already available, so we have to add Spanish labels.

**Comment by FranckCo** [comment]
Decided during 22 Feb. call: assign to Juan.

**Comment by DrJMunozMx** [comment]
The task is accepted,

**Comment by DrJMunozMx** [comment]
The task has been completed, please review the turtle file with the translation and accept the changes

**Comment by FranckCo** [comment]
Pull requested accepted, closing the issue.
