### ISSUE TITLE
Check coherence of textual properties

### ISSUE THREAD

**Issue by FranckCo** [linked-statistics/COOS#26]
Check coherent use of rdfs:label, rdfs:comment, skos:prefLabel, skos:definition, etc., between the different definitions.

**Comment by flo7894** [comment]
- Most COOS classes have a "rdfs:comment" stating something like "as defined by GAMSO/GSIM/GSBPM", coos:Task and coos:GSIMEntity have to be aligned. 
- Following lack a rdfs:comment  : coos:StatisticalOrganization, coos:NationalStatisticalInstitute, coos:InternationalAgency, coos:uses, coos:supports
- Is it expected at some point to publish the statistical metadata glossary as a conceptScheme ? if not should we add skos:definition and skos:scopeNote on the conceptScheme for the GSBPM in the COOS ?

**Comment by InKyungChoi** [comment]
@flo7894  @FlavioRizzolo Regarding the definition of statistical org, national stat org., there is a glossary of recently published UN Handbook on Statistical Organization: https://unstats.un.org/wiki/display/HSO/Glossary 

- Statistical organization: Organization, or unit within an organization, whose primary role is the production of official statistics.
- National statistical office: The main producer of official statistics in a country and/or the organization responsible for coordinating all activities related to the development, production, and dissemination of official statistics in the national statistical system.

**Comment by FlavioRizzolo** [comment]
I suggest the following definition put together from the definitions of _International Organization_ and _Statistical Organization_

**International (statistical) agency**: A body with an international membership, scope, or presence whose primary role is the production of official statistics.

**Comment by FlavioRizzolo** [comment]
Tentative property definitions:

**supports**: to enable to perform or function. _Activities_, e.g. GAMOS Manage Statistical Methods, support _Statistical Production Activities_, e.g. GSBPM Phases.
**uses**: to require to perform or function. _Statistical Production Activities_, e.g. GSBPM Overarching Processes, use _Activities_, e.g. Manage IT.

Uses and supports are inverses. They are weaker (looser) forms of dependencies than partitive relationships: uses/supports is about function whereas part/whole is about constitution.

**Comment by FranckCo** [comment]
Suggested definitions are integrated in the HTML and Turtle files. Remaining considerations in this issue are reported in issue #29.
Current issue is thus closed.

**Comment by JALinnerud** [comment]
See chapter 1C
https://unstats.un.org/unsd/methodology/dataquality/un-nqaf-manual/
National statistical office (NSO): the leading statistical agency within a
national statistical system. National statistical office and national statistical
institute mean the same thing. In general, the NSO has a coordination
n role within the national statistical system, and is responsible for the development,
production and dissemination of official statistics across multiple statistical
domains.
