### ISSUE TITLE
Links with Statistical Metadata Glossary

### ISSUE THREAD

**Issue by flo7894** [linked-statistics/COOS#29]
Phases, sub-processes of GSBPM are created as instances in the COOS turtle document. Currently there are no definition associated.

**Comment by FranckCo** [comment]
(from issue 26) Is it expected at some point to publish the statistical metadata glossary as a conceptScheme ? if not should we add skos:definition and skos:scopeNote on the conceptScheme for the GSBPM in the COOS ?

**Comment by InKyungChoi** [comment]
FYI - definition of phase and sub-process in [Metadata Glossary](https://statswiki.unece.org/display/hlgbas/Statistical+Metadata+Glossary) 

- Phase: distinct stage of the statistical business life cycle based on  interrelated activities addressing a given purpose
- Sub-process: distinct stage of the statistical business process that consists of interrelated activities

**Comment by InKyungChoi** [comment]
> Phases, sub-processes of GSBPM are created as instances in the COOS turtle document. Currently there are no definition associated.

FYI - definition of phase and sub-process in Metadata Glossary

Phase: distinct stage of the statistical business life cycle based on interrelated activities addressing a given purpose
Sub-process: distinct stage of the statistical business process that consists of interrelated activities

**Comment by InKyungChoi** [comment]
I remember that definitions of activity, statistical activity, etc. were discussed to some extent in separate places and time, but I don’t quite remember if there was already consensus made or they are still up for discussion with COOS team. If not, I wonder if it would be beneficial to have a look at all (vertically) related classes altogether in one go? 
 
![image](https://user-images.githubusercontent.com/10498769/119314105-9d868880-bc74-11eb-8c61-bd3158a3a1cd.png)

Below is the various definitions made for each term that I found, I made few proposals (bold highlighted ones) as well. 
 
### coos:Activity
- Metadata Glossary: “what we do”
- GAMSO: “what statistical organisations do”; but also it has “GAMSO describes and defines the activities that take place within a typical organisation that produces official statistics”
- GSBPM: this term is not defined
- Prov-O: “An activity is something that occurs over a period of time and acts upon or with entities; it may include consuming, processing, transforming, modifying, relocating, using, or generating entities”
- COOS (as of now): “Activity as defined by the GAMSO”

=> proposals

1. **(prov) activity that a statistical organization does**
2. (prov) activity that take place within a statistical organization
3. (prov) activity as scoped by the GAMSO
 
### coos:StatisticalActivity
- GAMSO: this term is not used in GAMSO
- COOS (as of now): “Generic statistical activity”

=> proposals
1.	Activity that has a direct relation to the production of statistics / Activity that has a direct relation to the production of statistics or support it
2.	Statistical production activity or activity that has a direct relation to it
3.	Statistical production activity or activity that directly supports it
 
###  coos:StatisticalProductionActivity
- GAMSO: this term is not used (“Statistical Production Process” is used instead in both GAMSO and GSBPM) 
- Coos (as of now): “Statistical production activity covered by the GSBPM”

=> proposals
1.	Statistical activity as scoped by the GSBPM
2.	Statistical activity that is conducted as a part of a process that results in the production of statistics
3.	**Statistical activity that is conducted as a part of a process to produce statistics**
 
### coos:Phase
- Metadata Glossary: “distinct stage of the statistical business life cycle based on interrelated activities addressing a given purpose”
- GSBPM: this term is not defined 
- COOS (as of now): “Process phase as defined by the GSBPM”

=> proposals
1.	**Statistical production activity that is conducted at a specific stage of a process as defined by GSBPM Phases**
 
### coos:Subprocess
- Metadata Glossary: “distinct stage of the statistical business process that consists of interrelated activities”
- GSBPM: this term is not defined 
- COOS (as of now): “Sub-process as defined by the GSBPM”

=> proposals
1.	Statistical production activity that is conducted at a specific stage of a process as defined by GSBPM sub-process and 
2.	**Statistical production activity that is scoped by a given Phase**
 
### coos:Task
- COOS (as of now): “Statistical activity scoped by a given GSBPM sub-process

=> proposals
1.	**Statistical production activity that is scoped by a given Subprocess**

**Comment by JALinnerud** [comment]
Inconsistency?
coos:Phase
•	GSBPM: this term is not defined
=> proposals
1.	Statistical production activity that is conducted at a specific stage of a process as defined by GSBPM Phases

**Comment by JALinnerud** [comment]
coos:Activity
•	Metadata Glossary: “what we do”
=> proposals
4.	what a statistical organisation does

**Comment by JALinnerud** [comment]
coos:StatisticalActivity
=> proposals
3.	Statistical production activity or activity that directly supports it

**Comment by JALinnerud** [comment]
Include Task in the figure?

**Comment by JALinnerud** [comment]
coos:StatisticalProductionActivity
=> proposals
4.	Statistical activity that is conducted as part of the production of statistics

**Comment by flo7894** [comment]
So far definitions for coos classes have been discussed. Do we also want definitions for coos individuals ?

**Comment by FranckCo** [comment]
We do not replicate SMG definitions for COOS now, so closing the issue. If use case appears, we will reopen.
