### ISSUE TITLE
Terminology: name of the top individual in the GSBPM concept scheme

### ISSUE THREAD

**Issue by FlavioRizzolo** [linked-statistics/COOS#3]
If the GSBPM is the concept scheme, then shouldn’t the top individual of that scheme be the GSBPM level 0? However, Level 0 is called statistical _business_ process rather than statistical _production_ process. Are we changing the GSBPM terminology? Or is statistical production process something entirely different?

**Comment by FranckCo** [comment]
Notes from March 7 meeting:
 - Check why StatisticalProductionProcess was chosen rather than StatisticalBusinessProcess.

**Comment by FranckCo** [comment]
Comments on the March 7 meeting notes:
 - This can be discussed, but we see in the GAMSO perspective that the GSBPM is actually focused on statistical production, so maybe it should be renamed Generic Statistical Production Process Model.

**Comment by InKyungChoi** [comment]
I see the discrepancy but the cost of changing name of GSBPM is.... quite high.......

> Comments on the March 7 meeting notes:
> 
> * This can be discussed, but we see in the GAMSO perspective that the GSBPM is actually focused on statistical production, so maybe it should be renamed Generic Statistical Production Process Model.

**Comment by FlavioRizzolo** [comment]
If it is indeed the same concept and we are really talking about GSBPM level 0, then I suggest to just rename the individual in COOS to statisticalBusinessProcess.

**Comment by FranckCo** [comment]
Decided during 7 May meeting: work on issue #10 first then come back to this one. For now the individual is named statisticalProductionProcess.

**Comment by DrJMunozMx** [comment]
![image](https://user-images.githubusercontent.com/1855266/60522668-0d6d7d80-9caf-11e9-93e8-46492e4610c9.png)

**Comment by FranckCo** [comment]
Decided during 19 September meeting: keep statisticalProductionProcess.
