### ISSUE TITLE
Should we include a class for architecture building blocks?

### ISSUE THREAD

**Issue by FranckCo** [linked-statistics/COOS#32]
The ```Capability``` class was created in commit f8a689e4982041a8be95564101a1bbf13a8e8bcd. Do we need to create also building block (used for example in CSDA)?

**Comment by JALinnerud** [comment]
Is CSDA in scope now or is it future work? See #22

**Comment by FranckCo** [comment]
Discussed during the May 3rd meeting: building blocks are specific to CSDA, no transverse use case identified.
