### ISSUE TITLE
Links to the Classification of Statistical Activities

### ISSUE THREAD

**Issue by FranckCo** [linked-statistics/COOS#33]
Should we define links between COOS and the CSA (https://statswiki.unece.org/display/CSA/CSA+Rev.+1)?

**Comment by JALinnerud** [comment]
In general, should we be more proactive about using existing terms and definitions? 
That was a design principle for GSIM, but we relied mostly on those from work created in NSI's 
Should we be looking more actively at sources such as:
adms http://www.w3.org/ns/adms# Asset Description Metadata Schema
dcat http://www.w3.org/ns/dcat# Data Catalog Vocabulary
dct http://purl.org/dc/terms/ DCMI Metadata Terms
foaf http://xmlns.com/foaf/0.1/ FOAF Vocabulary
locn http://www.w3.org/ns/locn# ISA Programme Core Location Vocabulary
owl http://www.w3.org/2002/07/owl# OWL Web Ontology Language
rdf http://www.w3.org/1999/02/22-rdf-syntaxns#
Resource Description Framework
rdfs http://www.w3.org/2000/01/rdf-schema# RDF Vocabulary Description Language 1.0:
RDF Schema
skos http://www.w3.org/2004/02/skos/core# SKOS Simple Knowledge Organization
System - Reference
vcard http://www.w3.org/2006/vcard/ns# vCard Ontology
xkos https://ddialliance.org/Specification/XKOS/
1.2/OWL/xkos.html
An SKOS extension for representing
statistical classifications
xsd http://www.w3.org/2001/XMLSchema# XML Schema

**Comment by JALinnerud** [comment]
Could CSA be used as a dcat:theme? For example for GSIM Subject Field as a way to group Data Sets etc?

**Comment by FranckCo** [comment]
dcat:theme (sub-property of dct:subject) was mentioned as a solution for the categorization of data sets by statistical domain (issue #33). The range of this property is skos:Concept, so using the CSA would require to formalize it as a SKOS concept scheme.
I have some reservations about CSA, which mixes actual statistical domains (domains 1, 2 and most of 3) with about anything else. The governance of the classification is also unclear.

**Comment by InKyungChoi** [comment]
In response to question "Who is the owner of CSA, what is the governance? Do we have authority to offer feedback to it? → @InKyung assigned to investigate" from meeting on 25th May: 

The owner of CSA is Conference of European Statistician (CES), but you can see UNECE (Secretariat of CES) as a manager. I don't know if there is any formal governance model, but it is currently being revised by a Task Team consisting of several national and international organisations. **If you have any input, you are absolutely welcome to share your thoughts.** I sent out an email to Supporting Standards and few others asking for inputs (7th December 2020). If you did not receive this and want me to send it to you, let me know.

**Comment by FranckCo** [comment]
Closing the issue for now as we don't have time to liaise with CSA custodians.
