### ISSUE TITLE
French translations for individuals

### ISSUE THREAD

**Issue by FranckCo** [linked-statistics/COOS#39]
Most of instances GAMSO and GSBPM instances do not have a French label

**Comment by flo7894** [comment]
Currently Insee uses an unofficial translation of phases and sub-processes' labels with verbs. But there is also one with nouns that has been adapted from version 5.0 translation.

**Comment by FranckCo** [comment]
Done in commit ff23a8fda3947ddb42f894dd47e1118af90514d8, so closing the issue.
