### ISSUE TITLE
Mapping to GSIM Business Group

### ISSUE THREAD

**Issue by FlavioRizzolo** [linked-statistics/COOS#4]
We need to include the GSIM Business Group into the picture. GSIM include **Statistical Program** and **Statistical Support Program** classes that are either top level activities that can be decomposed into lower level activities or some other type of activity grouping. Moreover, **Statistical Support Program** seems to align, to some extent, with _overarching processes_ in GSBPM. In addition, the notion of a cycle is missing from GSBPM and needs to be included in a core ontology. In GSIM it is well represented by **Statistical Program Cycle**.

**Comment by FranckCo** [comment]
coos:StatisticalProgram and coos:StatisticalProgramCycle are now part of COOS.

  * should we specify links between them and GSBPM/GAMSO artefacts?
  * do we need **Statistical Support Program**?

**Comment by FranckCo** [comment]
Decided during July 2 meeting: assign to Flavio

**Comment by FlavioRizzolo** [comment]
Proposed model extension including GSIM Statistical Support Program, Statistical Program and Statistical Program Cycle:

![image](https://user-images.githubusercontent.com/11507347/61757687-ab74d500-ad8f-11e9-946b-c32d6c856e34.png)

Statistical Support Activity was added to capture activities from GAMSO Corporate Support that has a statistical component, e.g. Manage Quality, Manage Statistical Methodology, Manage Information and Knowledge.

Statistical Development Program was added to capture Programs concern with the creation, change and maintenance of Statistical Programs (This seems to be somewhat related to GAMSO Capability Development).

**Comment by FlavioRizzolo** [comment]
Updated diagram with the removal of Statistical Support Activity:

![image](https://user-images.githubusercontent.com/11507347/65763029-73bc3d80-e0f0-11e9-9969-12fe66be44db.png)

**Comment by JALinnerud** [comment]
1) Statistical Program Cycle text refers twice to Statistical Program Design, but that is not included in the figure. 2) The text in the yellow box referring to BMN and task has deteriorated when shortened. As a minimum change application**s** to application. Perhaps just use the full text "A task is an atomic Activity within a Process flow. A Task is used when the work in the Process cannot be broken down to a finer level of detail. Generally speaking, either a worker  (human) or application (automation) perform necessary work representing the Task during execution." (omg.org BPMN 2) 3) GSBPM has Quality management, Metadata Management and Data Management in that order. Manage Quality listed as the second example in the figure could be moved first and renamed.

**Comment by InKyungChoi** [comment]
1. I wonder if _Statistical Program_ and _Statistical Support Program_ are just groups of sub-classes of _Statistical Production Activity_ (e.g. _Statistical Program_ corresponds to GSBPM Phase 4-8 and _Statistical Support Program_ corresponds to GSBPM phase 1-3, plus GSBPM overarching processes)...?
2. Shouldn't "Manage Quality" be _Statistical Activity_, not _Activity_? It seems as directly supporting _Statistical Production Activity_ as "Manage Statistical Methodologies"?

**Comment by pafrance** [comment]
About the relation between (1) GSBPM Business Process and (2) GSIM Statistical Program and (3) GSIM Statistical Support program.
I got that there was a kind of equivalence between the (1) and (2) but what about (1) and (3?) I ask this cause I have always assumed that the business process describes the same concept as the statistical program, with respect to the different context described in their own models of pertinence. So, I'd like to know if I am mistaking, as I'm using these models in several works in Istat too, and I'd like to be corrected while I still can. Thank you.
And If there's actually an equivalence or overlapping between these concepts, wouldn't it  be better to add these in the graph above too?

**Comment by JALinnerud** [comment]
Maybe we should exemplify with the Phases Design and Analyse rather than Design and Process?

**Comment by FranckCo** [comment]
Decided during during September 13th meeting: remove StatisticalSupportProgram class.

**Comment by FranckCo** [comment]
Following 9/7 meeting, close this issue and continue the discussion in issue #60
