### ISSUE TITLE
Additional questions about capabilities

### ISSUE THREAD

**Issue by FranckCo** [linked-statistics/COOS#46]
The Capability class is now included in the COOS. Additional questions, which are probably not for version 1.0 but for further developments:
 - Should we introduce the distinction made for example in CSDA between Core, Cross-cutting and Lower-level capabilities?
 - Should we define the capabilities listed in CSDA as COOS individuals?
 - Should we model the links between capabilities and statistical production activities?

**Comment by FlavioRizzolo** [comment]
Regarding:

> Should we introduce the distinction made for example in CSDA between Core, Cross-cutting and Lower-level capabilities?

I think we should, since Cross-Cutting and Core are well-defined:

- **Core capabilities**: capabilities the organization needs to execute its core business, i.e. the production of statistics. They generally map to “Corporate Support Activities” in GAMSO and “Overarching processes” in GSBPM.
- **Cross-cutting capabilities**: capabilities used to formulate and implement the policies that the organization chooses for its internal operations. They generally map to phases in GSBPM.

Lower-level capabilities are just sub-capabilities, they can be modeled with skos:broader, like sub-processes to phases, or better with part-of.

**Comment by InKyungChoi** [comment]
@FlavioRizzolo mapping between GSBPM/GAMSO and Core/Cross-cutting capabilities seems to be exchanged?

**Comment by FlavioRizzolo** [comment]
> @FlavioRizzolo mapping between GSBPM/GAMSO and Core/Cross-cutting capabilities seems to be exchanged?

Yes, I fixed it!  @InKyungChoi

**Comment by JALinnerud** [comment]
The ESS has a Business Capabilities model that might be worth checking https://joinup.ec.europa.eu/collection/statistical-enterprise-architecture/document/ess-earf-business-capabilities-model  
See Figure 2 ESS Business Capabilities model – Levels 0 & 1

**Comment by JALinnerud** [comment]
Some examples of capability development from Geostat4
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/jal/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/jal/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/jal/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-GB style='tab-interval:36.0pt;word-wrap:break-word'>




Engage to develop, use   and promote new standards
--
Insert location at the   core of the data architecture
Use services to increase   interoperability
Develop and share common   and reusable tools
Design and implement   Geospatial Reference Architecture for statistics
Ensure common conceptual   models and semantic interoperability across data domains
Define concepts of   kinetic statistics
Enable data integration   through services
Disseminate open data and   services
Develop and apply   services for smarter statistical-geospatial integration
Develop and apply common   concepts and tools for Linked Open Data
Explore publishing   reference data as Linked   Open Data




</body>

</html>

**Comment by JALinnerud** [comment]
Can we link GAMSO Capability Development to COOS "Capability"? 
Action: Jenny to propose a sentence and continue discussion on github issue
Capability Development: Development of capabilities that enable the organisation to undertake new activities, or to improve the efficiency of existing ones

**Comment by JALinnerud** [comment]
Some examples of capability development from Geostat4:

Engage to develop, use   and promote new standards
Insert location at the   core of the data architecture
Use services to increase   interoperability
Develop and share common   and reusable tools
Design and implement   Geospatial Reference Architecture for statistics
Ensure common conceptual   models and semantic interoperability across data domains
Define concepts of   kinetic statistics
Enable data integration   through services
Disseminate open data and   services
Develop and apply   services for smarter statistical-geospatial integration
Develop and apply common   concepts and tools for Linked Open Data
Explore publishing   reference data as Linked Open Data

**Comment by FlavioRizzolo** [comment]
> The ESS has a Business Capabilities model that might be worth checking https://joinup.ec.europa.eu/collection/statistical-enterprise-architecture/document/ess-earf-business-capabilities-model
> See Figure 2 ESS Business Capabilities model – Levels 0 & 1

I agree, that should be a core reference. We do use the ESS Business Capabilities model at StatCan, and it was also an inspiration for CSDA. This particular paragraph could shed some light on the alignment between business capabilities and functions:

> Business Capabilities are similar to Business Functions as defined in GSIM or CSPA. The difference between the two concepts lies in their orientation and level of detail. As an indication, Business Capabilities tend to be more strategy-driven and strategy-oriented as they serve to decide on investments whilst Business Functions are more process/activity-oriented and applicable in an operational context.  Further, Business Capabilities are typically expressed at higher levels of granularity (what is referred to as levels 0, 1 and 2 further below) whilst Business Functions are more fine-grained reflecting what one would express at Business Capability levels 3 and onwards. 

And this one between capabilities and activities:

> There is a many-to-many relationship between Business Capabilities and Activities. A capability can support different activities and on the opposite an activity can require different capabilities. Business capabilities tend to be defined so that they are reused across different activities ensuring that investments are efficient.

**Comment by FlavioRizzolo** [comment]
> Can we link GAMSO Capability Development to COOS "Capability"?

It makes sense, the question is how we do that since Capability Development is an individual and Capability is a class...

**Comment by FranckCo** [comment]
Relevant content integrated in specification, closing issue.
