### ISSUE TITLE
Third-level GAMSO activities?

### ISSUE THREAD

**Issue by FranckCo** [linked-statistics/COOS#67]
The notes of the second-level GAMSO activities are very well structured, so it would be possible to replace (or double) them with lists of individual concepts for third-level activities. For example, activity 2.1.1 ('Identify disruptions and capability improvements') would be created with a <code>skso:broader</code> link to the activity 2.1.

**Comment by JALinnerud** [comment]
The third level is not supposed to be complete. This might be a) misleading and/or b) a maintenance challenge,

**Comment by FranckCo** [comment]
4th July meeting decided to close.
