### ISSUE TITLE
Feedback from Jenny Linnerud on the COOS main document

### ISSUE THREAD

**Issue by JALinnerud** [linked-statistics/COOS#68]
[COOS - feedback_20211031.docx](https://github.com/linked-statistics/COOS/files/7427265/COOS.-.feedback_20211031.docx)

**Comment by FranckCo** [comment]
Typos fixed in a5fe3c9.

**Comment by FranckCo** [comment]
Substantive comments incorporated in https://github.com/linked-statistics/COOS/commit/b0082b9ac0b986cd11ca83aaf00b83d3edf33ff3.

Closing the issue.
