### ISSUE TITLE
Feedback from Thérèse Lalor 

### ISSUE THREAD

**Issue by thereselalor** [linked-statistics/COOS#70]
[Feedback from Therese Lalor.docx](https://github.com/linked-statistics/COOS/files/7451410/Feedback.from.Therese.Lalor.docx)

**Comment by FlavioRizzolo** [comment]
See changes to Intro in issue #42

**Comment by FranckCo** [comment]
Feedback discussed and incorporated in commits https://github.com/linked-statistics/COOS/commit/8fe20fca2c49ae7a6bfaebb21c5c48cf70e7a106 and https://github.com/linked-statistics/COOS/commit/0fe458f4d6a275d4c4c3b73c3baf5bad6ae8ff6d.
